

--create table user_authority (
--    authority varchar(255) not null,
--    primary key (authority)
--)
--
--create table user_details (
--    id bigint generated by default as identity (start with 1),
--    username varchar(255) not null,
--    password varchar(255) not null,
--    name varchar(255) not null,
--    enabled boolean not null,
--    administrator boolean not null,
--    create_date timestamp not null,
--    last_updated_date timestamp not null,
--    last_login_date timestamp,
--    number_of_visits integer not null,
--    primary key (id)
--)
--
--create table user_details_authorities (
--    user_details bigint not null,
--    authorities bigint not null
--)

INSERT INTO user_authority (authority) VALUES ('ROLE_USER');
INSERT INTO user_authority (authority) VALUES ('ROLE_ADMIN');

INSERT INTO user_details (id, version, username, password, first_name, last_name, enabled, create_date, last_updated_date, number_of_visits)
 VALUES (null, 1, 'mburns', '$2a$10$/k9NgqPafRMPSYv19/XhLOjktrIgZB13kcDT9R/.hsIQ1Mg/Zy85.', 'Mark', 'Burns', true, '2014-05-01 07:00:00', '2014-05-01 07:00:00', 0);

INSERT INTO user_details (id, version, username, password, first_name, last_name, enabled, create_date, last_updated_date, number_of_visits)
 VALUES (null, 1, 'jaskren', '$2a$10$/k9NgqPafRMPSYv19/XhLOjktrIgZB13kcDT9R/.hsIQ1Mg/Zy85.', 'Jay', 'Askren', true, '2014-06-11 08:22:00', '2014-06-11 08:45:00', 0);

INSERT INTO user_details (id, version, username, password, first_name, last_name, enabled, create_date, last_updated_date, number_of_visits)
 VALUES (null, 1, 'jharris', '$2a$10$/k9NgqPafRMPSYv19/XhLOjktrIgZB13kcDT9R/.hsIQ1Mg/Zy85.', 'Jacob', 'Harris', false, '2014-11-21 08:35:00', '2014-11-21 15:12:00', 0);

INSERT INTO user_details (id, version, username, password, first_name, last_name, enabled, create_date, last_updated_date, number_of_visits)
 VALUES (null, 1, 'allen', '$2a$10$/k9NgqPafRMPSYv19/XhLOjktrIgZB13kcDT9R/.hsIQ1Mg/Zy85.', 'Jeff', 'Allen', false, '2014-11-21 08:35:00', '2014-11-21 15:12:00', 0);


INSERT INTO user_details_authorities (user_details, authorities) VALUES (1, 'ROLE_USER');
INSERT INTO user_details_authorities (user_details, authorities) VALUES (1, 'ROLE_ADMIN');
INSERT INTO user_details_authorities (user_details, authorities) VALUES (2, 'ROLE_USER');
INSERT INTO user_details_authorities (user_details, authorities) VALUES (2, 'ROLE_ADMIN');
INSERT INTO user_details_authorities (user_details, authorities) VALUES (3, 'ROLE_USER');
INSERT INTO user_details_authorities (user_details, authorities) VALUES (3, 'ROLE_ADMIN');
INSERT INTO user_details_authorities (user_details, authorities) VALUES (4, 'ROLE_USER');
INSERT INTO user_details_authorities (user_details, authorities) VALUES (4, 'ROLE_ADMIN');


INSERT INTO project (id, guid, name, create_date, last_updated_date)
 VALUES (1000, 'ed3f7081-bfb4-4857-9b39-2f73657f67d1', 'PDF Test Project', '2014-05-01 07:00:00', '2014-05-01 07:00:00');

INSERT INTO project (id, guid, name, create_date, last_updated_date)
 VALUES (null, 'd5df53c6-2933-484c-882b-94f091ecb1af', 'TIFF Test Project', '2014-05-01 07:00:00', '2014-05-01 07:00:00');

 INSERT INTO container (id, parent_id, project_id, name, container_type, guid, srcguid, create_date, last_updated_date)
  VALUES (1000, -1, 1000, 'Batch_1', 0, '1ca28e25-1b2a-498f-8f5b-b043a2fd13a0', '[]', '2014-05-01 07:00:00', '2014-05-01 07:00:00');

 INSERT INTO container (id, parent_id, project_id, name, container_type, guid, srcguid, create_date, last_updated_date)
  VALUES (1001, 1000, 1000, 'Batch_1', 0, '1ca28e25-1b2a-498f-8f5b-b043a2fd14b0', '[]', '2014-05-01 07:00:00', '2014-05-01 07:00:00');

 INSERT INTO container (id, parent_id, project_id, name, container_type, guid, srcguid, create_date, last_updated_date)
  VALUES (1002, 1001, 1000, 'PKJ_20111001-20111231_03', 0, '35a3bb14-1564-4de7-9927-10fa6c2968e6', '[]', '2014-05-01 07:00:00', '2014-05-01 07:00:00');
